server:
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
ingester:
  trace_idle_period: 30s
  max_block_bytes: 5000000
  max_block_duration: 1m
compactor:
  compaction:
    block_retention: 168h
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

memberlist:
  join_members:
    - "tempo:7946"
  bind_port: 7946